name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '* 1 * * *'
    # scheduled for every 1hr
  push:
    paths:
      - '.github/workflows/upstream.yaml'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: geerlingguy/docker-centos7-ansible      # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: master          # set the branch to merge to
